### PR TITLE
feature:add k3heap

### PR DESCRIPTION
**Pull request by IloveKanade**
The heap module has been modified according to the specification

### CODE REVIEW

**Review by drmingdrmer — APPROVED** [review]
LGTM

**Comment by drmingdrmer** [comment]
By the way you do not need to modify anything in `_building`.

**Review by pengsven — APPROVED** [review]

**Comment by IloveKanade** [comment]
> By the way you do not need to modify anything in `_building`.

okay, I'll pay attention next time

**Comment by IloveKanade** [comment]
> By the way you do not need to modify anything in `_building`.

I want to know if the tml in the _building directory needs to be removed? I don't see that in the jobq project

**Comment by drmingdrmer** [comment]
> > By the way you do not need to modify anything in `_building`.
> 
> I want to know if the tml in the _building directory needs to be removed? I don't see that in the jobq project

These are building script etc in `_building`. 
`tmpl` is added after `jobq` is created, thus `jobq` lacks these script but the pip package itself works well. 
An update of `_building` to `jobq` would be enough to fix this gap.

**Comment by drmingdrmer** [comment]
Seems it is a good time to fire the first publish!

**Comment by IloveKanade** [comment]
> > > By the way you do not need to modify anything in `_building`.
> > 
> > 
> > I want to know if the tml in the _building directory needs to be removed? I don't see that in the jobq project
> 
> These are building script etc in `_building`.
> `tmpl` is added after `jobq` is created, thus `jobq` lacks these script but the pip package itself works well.
> An update of `_building` to `jobq` would be enough to fix this gap.

but if having tml causes CI on Git to fail, can this be ignored?

**Comment by drmingdrmer** [comment]
> but if having tml causes CI on Git to fail, can this be ignored?

🤔 not possible. Fire a PR with tmpl and let's have a look?

**Comment by drmingdrmer** [comment]
BTW the API doc in the old README need to be migrated to python doc. Like this:

https://github.com/pykit3/k3proc/blob/9a7f134b25828c17e0979044da6c183863eac538/proc.py#L25-L42

**Pull request merged**
